apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cheuser-che-route
  namespace: traefik-che
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/whoami`)
    kind: Rule
    services:
    - name: whoami
      namespace: cheuser-che
      port: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: cheuser-che-2-route
  namespace: traefik-che
spec:
  entryPoints:
    - web
  routes:
  - match: PathPrefix(`/whoami2`)
    kind: Rule
    services:
    - name: whoami
      namespace: cheuser-che-2
      port: 8080
